blank_issues_enabled: false
contact_links:
  - name: Mod Page (KingMods)
    url: https://www.kingmods.net/en/fs25/mods/74020/income-mod
    about: Leave comments or questions on the official mod page.
